defmodule PyqRatta.Repo.Migrations.QuestionNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:quiz_questions) do
      add :question_number, :bigint
    end
  end

  def down do
    alter table(:quiz_questions) do
      remove :question_number
    end
  end
end