defmodule PyqRatta.Repo.Migrations.Users do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :email, :citext
      add :telegram_id, :decimal, null: false
      add :email_verified, :boolean
      add :tg_firstname, :citext
      add :tg_lastname, :citext
      add :daily_goal, :bigint, default: 10
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:users, [:telegram_id], name: "users_unique_telegram_id_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:telegram_id], name: "users_unique_telegram_id_index")

    drop table(:users)
  end
end
