defmodule PyqRatta.Repo.Migrations.QuizQuestionsManyMany do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quiz_questions, primary_key: false) do
      add :quiz_id, :uuid, null: false, primary_key: true
      add :question_id, :uuid, null: false, primary_key: true
    end

    create table(:quiz, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:quiz_questions) do
      modify :quiz_id,
             references(:quiz,
               column: :id,
               name: "quiz_questions_quiz_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:quiz) do
      add :short_description, :text
      add :long_description, :text
      add :year, :bigint
      add :tags, {:array, :text}, default: []
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:question, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:quiz_questions) do
      modify :question_id,
             references(:question,
               column: :id,
               name: "quiz_questions_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:question) do
      add :question_text, :text
      add :question_image, :text
      add :type, :text
      add :correct_answer_text, :text, null: false
      add :correct_answer_image, :text
      add :explanation_text, :text
      add :explanation_image, :text
      add :short_description, :text
      add :long_description, :text
      add :year, :bigint
      add :tags, {:array, :text}, default: []
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:question) do
      remove :updated_at
      remove :created_at
      remove :tags
      remove :year
      remove :long_description
      remove :short_description
      remove :explanation_image
      remove :explanation_text
      remove :correct_answer_image
      remove :correct_answer_text
      remove :type
      remove :question_image
      remove :question_text
    end

    drop constraint(:quiz_questions, "quiz_questions_question_id_fkey")

    alter table(:quiz_questions) do
      modify :question_id, :uuid
    end

    drop table(:question)

    alter table(:quiz) do
      remove :updated_at
      remove :created_at
      remove :tags
      remove :year
      remove :long_description
      remove :short_description
    end

    drop constraint(:quiz_questions, "quiz_questions_quiz_id_fkey")

    alter table(:quiz_questions) do
      modify :quiz_id, :uuid
    end

    drop table(:quiz)

    drop table(:quiz_questions)
  end
end