defmodule PyqRatta.Repo.Migrations.Response do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_quiz_response, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :attempted_answer, :text, null: false
      add :retry_at, :utc_datetime
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_quiz_response_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :quiz_id,
          references(:quiz,
            column: :id,
            name: "user_quiz_response_quiz_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :question_id,
          references(:question,
            column: :id,
            name: "user_quiz_response_question_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:user_quiz_response, "user_quiz_response_user_id_fkey")

    drop constraint(:user_quiz_response, "user_quiz_response_quiz_id_fkey")

    drop constraint(:user_quiz_response, "user_quiz_response_question_id_fkey")

    drop table(:user_quiz_response)
  end
end
