defmodule PyqRatta.Repo.Migrations.AddSourceToQuestion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:question) do
      add :source, :text
    end
  end

  def down do
    alter table(:question) do
      remove :source
    end
  end
end