defmodule PyqRatta.Repo.Migrations.AddQuestion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:question, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :question_text, :text
      add :question_image, :text
      add :type, :text
      add :correct_answer_text, :text, null: false
      add :correct_answer_image, :text
      add :explanation_text, :text
      add :explanation_image, :text
      add :short_description, :text
      add :long_description, :text
      add :year, :bigint
      add :tags, {:array, :text}, default: []
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    drop table(:question)
  end
end